args: Enable user directory placeholder path expansion
First expand user directory placeholders before attempting to evaluate
os.path.realpath. Without doing so, results will treat '~' as a relative
directory similar to '.'.

Example of result before fix

  ValueError: Kernel path '/home/binary-eater/Documents/mlx/mkt/~/Documents/mlx/linux' is not a directory/does not exist

Signed-off-by: Rahul Rameshbabu <rrameshbabu@nvidia.com>