run: Fix failure if no config file is used
mlx{jgg}~/oss/kvm#mkt run --kernel `pwd` --dir ~/oss/rdma-core --simx cx5-ib
Traceback (most recent call last):
  File "/home/jgg/dotfiles/bin/mkt", line 23, in <module>
    utils.cmdline.main(cmd_modules, plugins)
  File "/home/jgg/mlx/x-tools/utils/cmdline.py", line 145, in main
    args.func(args)
  File "/home/jgg/mlx/x-tools/plugins/cmd_run.py", line 397, in cmd_run
    args.boot_script = validate_and_set_boot(args)
  File "/home/jgg/mlx/x-tools/plugins/cmd_run.py", line 250, in
validate_and_set_boot
    args.boot_script = utils.get_images(args.image)['boot_script']
TypeError: list indices must be integers or slices, not str

Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
Signed-off-by: Leon Romanovsky <leonro@mellanox.com>