ci: Add missing oython-ply module to fix SPDX check
Traceback (most recent call last):
  File "scripts/spdxcheck.py", line 6, in <module>
    from ply import lex, yacc
ImportError: No module named ply

Fixes: c0f985cedf79 ("ci: Run kernel checkpatch")
Signed-off-by: Leon Romanovsky <leonro@mellanox.com>