image: Add rst2man binary needed to built new rdma-core
error: Failed build dependencies:
        /usr/bin/rst2man is needed by rdma-core-25.0-1.fc30.x86_64

Signed-off-by: Leon Romanovsky <leonro@mellanox.com>