Move VFIO functions to separate file
Latest image changes caused to the situation where we called to mkt
files with wrong user because of sudo.

_  mkt git:(setups) mkt run
'nps-server-14' machine doesn't exist in
'/root/.config/mellanox/mkt/hv-nps-server-14.mkt'.
Please run setup before. Exiting ...
Traceback (most recent call last):
  File "/labhome/leonro/src/mkt//mkt", line 22, in <module>
    utils.cmdline.main(cmd_modules, plugins)
  File "/.autodirect/swgwork/leonro/src/mkt/utils/cmdline.py", line 84,
in main
    args.func(args)
  File "/.autodirect/swgwork/leonro/src/mkt/plugins/cmd_run.py", line
330, in cmd_run
    ["--pci=%s" % (I) for I in args.pci])
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo',
'/labhome/leonro/src/mkt//mkt', 'vfio-enable', '--pci=0000:05:00.0',
'--pci=0000:88:00.0']'
 returned non-zero exit status 1.

As an outcome of this change, the "mkt -h" won't present internal
vfio-enable command tot eh users.

Signed-off-by: Leon Romanovsky <leonro@mellanox.com>